// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR03v10eHd65c_tnGBRVWM7njyYR69x3k',
    appId: '1:639255741833:web:ea97ff6e08f4a687fdcd58',
    messagingSenderId: '639255741833',
    projectId: 'iti-summer-training',
    authDomain: 'iti-summer-training.firebaseapp.com',
    storageBucket: 'iti-summer-training.appspot.com',
    measurementId: 'G-J3E39KT8YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCiBbdW0Ygk9SIME2YYM1COgMWbDoyW7E',
    appId: '1:639255741833:android:39fdd231c5046022fdcd58',
    messagingSenderId: '639255741833',
    projectId: 'iti-summer-training',
    storageBucket: 'iti-summer-training.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX5ggT-Ehu8XctsTVZQ0cgNOq1RiJXr4c',
    appId: '1:639255741833:ios:b3f542713ca2b160fdcd58',
    messagingSenderId: '639255741833',
    projectId: 'iti-summer-training',
    storageBucket: 'iti-summer-training.appspot.com',
    iosClientId: '639255741833-ntah8oge8l95opcjbkb2iouqkrlor1qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.itiGraduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX5ggT-Ehu8XctsTVZQ0cgNOq1RiJXr4c',
    appId: '1:639255741833:ios:5e0042814752d5f6fdcd58',
    messagingSenderId: '639255741833',
    projectId: 'iti-summer-training',
    storageBucket: 'iti-summer-training.appspot.com',
    iosClientId: '639255741833-t9ua2f4ehn0rh8dq8su3m0ovk2prqgbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.itiGraduationProject.RunnerTests',
  );
}
